name: Update Resume Gist
on: push
jobs:
  update-resume-gist:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.RESUME_GIST_TOKEN }}
        gist_id: 3e4323d8bb1d859a19e97bddb1bd06cf
        file_path: resume.json
